[tool.poetry]
name = "practice-10-1"
version = "0.1.0"
description = ""
authors = ["Lyudmila Smirnova <lyuddmila@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
